### ISSUE TITLE
SEO fields populate also into Custom form fields (repeater) on Static Pages

### ISSUE THREAD

**Issue by corneliuscz** [Magiczne/october-seo-tweaker#2]
If a Static page layout extends form fields of a page with a repeater field then fields included in the repeater are also populated with the SEO fields from this plugin.

#### Step 1 

Create a layout page template for Static page and use this code to add a custom repeater field (a richeditor for example):
```
{repeater name="rep_field" prompt="Repeated Field Prompt" tab="Repeater Fields Tab"}
    {variable type="richeditor" name="rep_field_text" label="Field Label"}{/variable}
{/repeater}
```

#### Step 2

Edit page in Static pages section of the CMS and add new item of repeater field.

#### Step 3

See the result.
![extra-seo-fields-on-repeater](https://user-images.githubusercontent.com/1612073/118970906-12a14780-b96f-11eb-9586-d90213eb373e.png)

### Solution

The solution for this is quite simple. Add these lines in the file Plugin.php on line 31 (right after `Event::listen('backend.form.extendFieldsBefore', function (Form $form) {`:
```
if ($form->isNested) {
    return;
}   
```
These three lines prevent the backend.form listener from adding your fields to subsections.

If necessary I can make a pull request but thought that this might be the easiest and quickest way how to solve it.

Best,
Josef

**Comment by Magiczne** [comment]
I'll happily accept PR

**Comment by corneliuscz** [comment]
> I'll happily accept PR

OK, I'll try to create one, hopefuly will work :)
